import { IProduct } from "./iproduct.interface";

export const PRODUCTS: IProduct[] = [
    {
        id: 1,
        name: "Backpack",
        price: 50,
        description: "Backpack for travelling",
        image: "backpack.jpg",
        category: "Bags",
        brand: "Nikey",
        quantity: 1,
        availability: true,
    },
    {
        id: 2,
        name: "Small luggage",
        price: 100,
        description: "Small carry-on luggage for travelling",
        image: "small luggage.jpg",
        category: "Bags",
        brand: "Catitas",
        quantity: 1,
        availability: true,
    },
    {
        id: 3,
        name: "Women's dress",
        price: 35,
        description: "Long red women's night dress",
        image: "dress.jpg",
        category: "Clothes",
        brand: "H&Cat",
        quantity: 1,
        availability: true,
    },
    {
        id: 4,
        name: "Women's trouser",
        price: 45,
        description: "Beige tight trouser for women",
        image: "trouser.jpg",
        category: "Clothes",
        brand: "H&Cat",
        quantity: 1,
        availability: false,
    },
    {
        id: 5,
        name: "Women's snickers",
        price: 140,
        description: "Comfortable and purple women's snickers for summer",
        image: "snickers.jpg",
        category: "Shoes",
        brand: "Catverse",
        quantity: 1,
        availability: true,
    },
    {
        id: 6,
        name: "Beach hat",
        price: 20,
        description: "Beige women beach hat",
        image: "beach hat.jpg",
        category: "Clothes",
        brand: "Hatcat",
        quantity: 1,
        availability: true,
    },
    {
        id: 7,
        name: "Women's shoulder bag",
        price: 65,
        description: "Women's shoulder bag for a daily wear. Black imitation leather small bag",
        image: "shoulder bag.jpg",
        category: "Bags",
        brand: "Catto",
        quantity: 1,
        availability: true,
    },
    {
        id: 8,
        name: "Women's winter coat",
        price: 265,
        description: "Women's winter coat with navy blue colour.",
        image: "winter coat.jpg",
        category: "Clothes",
        brand: "Catombia",
        quantity: 1,
        availability: false,
    },
    {
        id: 9,
        name: "Women's jacket",
        price: 390,
        description: "Women's leather jacket for a daily wear. Black leather jacket is perfect for spring.",
        image: "jacket.jpg",
        category: "Clothes",
        brand: "Catto",
        quantity: 1,
        availability: true,
    },
]